server:
  port: 9001
  servlet:    context-path: /uaa

spring:
  h2:
    console:
      path: /h2-console
      enabled: true
      
  security:
    user:
      name: user
      password: 1234
            
security:  oauth2:    client:      client-secret: bar
      client-id: foo
      authorized-grant-types:      - authorization_code
      scope:      - openid
      